### ISSUE TITLE
FatalErrorException in AutologinServiceProvider

### ISSUE THREAD

**Issue by pkunze** [dwightwatson/autologin#12]
I get a `FatalErrorException` within `AutologinServiceProvider` when I integrate Autoupdate freshly in my Laravel 5 app. I wasn't able to resolve the source of error so far, which is why i raise this issue here.

![bildschirmfoto 2015-03-12 um 20 53 10](https://cloud.githubusercontent.com/assets/1416798/6626841/1b269250-c8fa-11e4-9116-dbcd0390a801.png)

I have played around with some settings in the config-file (`autologin.php`), but as you might suspect, i was not able to solve this. 

Some other information that might be helpful is that im using Entrust for roles and permission but no other package that is suspicious in this case.

These are all the packages included in my app (extract from my `composer.json`-file):

    "require": {
		"laravel/framework": "5.0.*",
		"illuminate/html": "5.0.*",
		"filp/whoops": "~1.0",
        "zizaco/entrust": "dev-laravel-5",
        "watson/autologin": "0.3.*"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1",
		"way/generators": "~3.0"
	},

I hope that this is somewhat helpful. If you need any further information or if there is any other way how i could be helpful, please let me know! Thanks in advance!

**Comment by dwightwatson** [comment]
What do you have set as `autologin_provider`? I've had a look at Entrust and it seems like it just adds roles, it doesn't have much to do with authentication, so it shouldn't be the issue here.

**Comment by dwightwatson** [comment]
Alright, this has absolutely nothing to do with Entrust and was just a bug in my upgrading to Laravel 5. I've pushed out a new release, `0.3.1` which should do the trick. Giving it a good test now.

**Comment by pkunze** [comment]
Awesome! Yeah, thats what i meant with thinking that entrust uses Laravels Auth-System in the Background! Thanks for the quick reaction!

**Comment by dwightwatson** [comment]
No worries, it seems like it's all working as expected now - just wasn't upgraded for Laravel 5 properly. I'll close the issue now but let me know if you have any other problems with it.
