### ISSUE TITLE
Database Migrations not published in L5

### ISSUE THREAD

**Issue by pkunze** [dwightwatson/autologin#13]
I've just found quite a minor issue. The Migrations aren't published by default, so that the Tables are missing on a virgin install.

Im not experienced in Package Dev but I suppose it could be solved by adding sth. like

    $this->publishes([
        __DIR__.'/../database/migrations/' => base_path('/database/migrations')
    ], 'migrations');

to `Watson\Autologin\AutologinServiceProvider->boot()`

Hope this helps!

**Comment by dwightwatson** [comment]
I published a [0.3.2](https://github.com/dwightwatson/autologin/commit/21b3071feecf17f0b44ced1ee1f7c52aed52291b) release shortly after the fix earlier today. I'm not sure migrations publish automatically in Laravel 5 (they didn't in Laravel 4) but the readme now contains the commands to publish the config and migrations for your project.

**Comment by pkunze** [comment]
Alright, sorry, didn't see that.

**Comment by dwightwatson** [comment]
No worries, was going to say let me know if it doesn't work but I'll assume now that it's okay!
