### ISSUE TITLE
how long do the token stay available?

### ISSUE THREAD

**Issue by Jossnaz** [dwightwatson/autologin#18]
how long do the token stay available?

i had some tokens malfunction and not sure why

how long are they available, when do they get deleted, how can i stop them from getting deleted?

**Comment by dwightwatson** [comment]
Have a look at the [config.php](https://github.com/dwightwatson/autologin/blob/master/src/config/config.php) file to see the default configuration options - you can always override them in your own app depending on what you need.

By default a token stays valid for 1440 minutes - one day from the time they are created. They are deleted when they expire, but you can change that if you like.

If you've got more detailed information about what is going wrong in your project along with some sample code to demonstrate the issue I'll be more than happy to take a look.

**Comment by Jossnaz** [comment]
I figured out one has to publish the config file first (whops)
